#####################
#####################
ROOTCFLAGS:=$(shell ${ROOTSYS}/bin/root-config --cflags)
ROOTGLIBS:=$(shell ${ROOTSYS}/bin/root-config --glibs)
#####################
CXX= g++
CXXFLAGS=-O2 -g -fPIC -Wall -Wno-unused
