/********************************************************************
* Scenar_t_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Scenar_t_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableScenar_t_dict();
extern void G__cpp_setup_inheritanceScenar_t_dict();
extern void G__cpp_setup_typetableScenar_t_dict();
extern void G__cpp_setup_memvarScenar_t_dict();
extern void G__cpp_setup_globalScenar_t_dict();
extern void G__cpp_setup_memfuncScenar_t_dict();
extern void G__cpp_setup_funcScenar_t_dict();
extern void G__set_cpp_environmentScenar_t_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ZAI.hxx"
#include "IsotopicVector.hxx"
#include "Scenar_t.hxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Scenar_t_dictLN_TClass;
extern G__linked_taginfo G__Scenar_t_dictLN_TBuffer;
extern G__linked_taginfo G__Scenar_t_dictLN_TMemberInspector;
extern G__linked_taginfo G__Scenar_t_dictLN_TObject;
extern G__linked_taginfo G__Scenar_t_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__Scenar_t_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Scenar_t_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Scenar_t_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Scenar_t_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Scenar_t_dictLN_ZAI;
extern G__linked_taginfo G__Scenar_t_dictLN_IsotopicVector;
extern G__linked_taginfo G__Scenar_t_dictLN_lesslEZAIgR;
extern G__linked_taginfo G__Scenar_t_dictLN_allocatorlEpairlEconstsPZAIcOdoublegRsPgR;
extern G__linked_taginfo G__Scenar_t_dictLN_maplEZAIcOdoublecOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__Scenar_t_dictLN_pairlEZAIcOdoublegR;
extern G__linked_taginfo G__Scenar_t_dictLN_maplEZAIcOdoublecOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOdoublegRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__Scenar_t_dictLN_maplEZAIcOdoublecOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOdoublegRsPgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__Scenar_t_dictLN_pairlEmaplEZAIcOdoublecOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOdoublegRsPgRsPgRcLcLiteratorcOboolgR;
extern G__linked_taginfo G__Scenar_t_dictLN_vectorlEZAIcOallocatorlEZAIgRsPgR;
extern G__linked_taginfo G__Scenar_t_dictLN_reverse_iteratorlEvectorlEZAIcOallocatorlEZAIgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Scenar_t_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__Scenar_t_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Scenar_t_dictLN_Scenar_t;
extern G__linked_taginfo G__Scenar_t_dictLN_vectorlEIsotopicVectormUcOallocatorlEIsotopicVectormUgRsPgR;
extern G__linked_taginfo G__Scenar_t_dictLN_vectorlEIsotopicVectormUcOallocatorlEIsotopicVectormUgRsPgRcLcLiterator;
extern G__linked_taginfo G__Scenar_t_dictLN_reverse_iteratorlEvectorlEIsotopicVectormUcOallocatorlEIsotopicVectormUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef map<ZAI,double,less<ZAI>,allocator<pair<const ZAI,double> > > G__maplEZAIcOdoublecOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOdoublegRsPgRsPgR;
typedef pair<ZAI,double> G__pairlEZAIcOdoublegR;
typedef vector<IsotopicVector*,allocator<IsotopicVector*> > G__vectorlEIsotopicVectormUcOallocatorlEIsotopicVectormUgRsPgR;
