//
// File generated by rootcint at Mon Jun  2 14:45:53 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME CLASSBackEndDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "CLASSBackEndDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void CLASSBackEnd_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_CLASSBackEnd(void *p = 0);
   static void *newArray_CLASSBackEnd(Long_t size, void *p);
   static void delete_CLASSBackEnd(void *p);
   static void deleteArray_CLASSBackEnd(void *p);
   static void destruct_CLASSBackEnd(void *p);
   static void streamer_CLASSBackEnd(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::CLASSBackEnd*)
   {
      ::CLASSBackEnd *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::CLASSBackEnd >(0);
      static ::ROOT::TGenericClassInfo 
         instance("CLASSBackEnd", ::CLASSBackEnd::Class_Version(), "./../include/CLASSBackEnd.hxx", 41,
                  typeid(::CLASSBackEnd), DefineBehavior(ptr, ptr),
                  &::CLASSBackEnd::Dictionary, isa_proxy, 0,
                  sizeof(::CLASSBackEnd) );
      instance.SetNew(&new_CLASSBackEnd);
      instance.SetNewArray(&newArray_CLASSBackEnd);
      instance.SetDelete(&delete_CLASSBackEnd);
      instance.SetDeleteArray(&deleteArray_CLASSBackEnd);
      instance.SetDestructor(&destruct_CLASSBackEnd);
      instance.SetStreamerFunc(&streamer_CLASSBackEnd);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::CLASSBackEnd*)
   {
      return GenerateInitInstanceLocal((::CLASSBackEnd*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CLASSBackEnd*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *CLASSBackEnd::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *CLASSBackEnd::Class_Name()
{
   return "CLASSBackEnd";
}

//______________________________________________________________________________
const char *CLASSBackEnd::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CLASSBackEnd*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int CLASSBackEnd::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CLASSBackEnd*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void CLASSBackEnd::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CLASSBackEnd*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *CLASSBackEnd::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CLASSBackEnd*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void CLASSBackEnd::Streamer(TBuffer &R__b)
{
   // Stream an object of class CLASSBackEnd.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      CLASSFacility::Streamer(R__b);
      {
         vector<IsotopicVector> &R__stl =  fIVArray;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            IsotopicVector R__t;
            R__t.Streamer(R__b);
            R__stl.push_back(R__t);
         }
      }
      R__b.CheckByteCount(R__s, R__c, CLASSBackEnd::IsA());
   } else {
      R__c = R__b.WriteVersion(CLASSBackEnd::IsA(), kTRUE);
      CLASSFacility::Streamer(R__b);
      {
         vector<IsotopicVector> &R__stl =  fIVArray;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<IsotopicVector>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            ((IsotopicVector&)(*R__k)).Streamer(R__b);
            }
         }
      }
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void CLASSBackEnd::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class CLASSBackEnd.
      TClass *R__cl = ::CLASSBackEnd::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fIVArray", (void*)&fIVArray);
      R__insp.InspectMember("vector<IsotopicVector>", (void*)&fIVArray, "fIVArray.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fOutBackEndFacility", &fOutBackEndFacility);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fIsStorageType", &fIsStorageType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fDecayDataBase", &fDecayDataBase);
      CLASSFacility::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_CLASSBackEnd(void *p) {
      return  p ? new(p) ::CLASSBackEnd : new ::CLASSBackEnd;
   }
   static void *newArray_CLASSBackEnd(Long_t nElements, void *p) {
      return p ? new(p) ::CLASSBackEnd[nElements] : new ::CLASSBackEnd[nElements];
   }
   // Wrapper around operator delete
   static void delete_CLASSBackEnd(void *p) {
      delete ((::CLASSBackEnd*)p);
   }
   static void deleteArray_CLASSBackEnd(void *p) {
      delete [] ((::CLASSBackEnd*)p);
   }
   static void destruct_CLASSBackEnd(void *p) {
      typedef ::CLASSBackEnd current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_CLASSBackEnd(TBuffer &buf, void *obj) {
      ((::CLASSBackEnd*)obj)->::CLASSBackEnd::Streamer(buf);
   }
} // end of namespace ROOT for class ::CLASSBackEnd

namespace ROOT {
   void vectorlEIsotopicVectorgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEIsotopicVectorgR_Dictionary();
   static void *new_vectorlEIsotopicVectorgR(void *p = 0);
   static void *newArray_vectorlEIsotopicVectorgR(Long_t size, void *p);
   static void delete_vectorlEIsotopicVectorgR(void *p);
   static void deleteArray_vectorlEIsotopicVectorgR(void *p);
   static void destruct_vectorlEIsotopicVectorgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<IsotopicVector>*)
   {
      vector<IsotopicVector> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<IsotopicVector>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<IsotopicVector>", -2, "prec_stl/vector", 49,
                  typeid(vector<IsotopicVector>), DefineBehavior(ptr, ptr),
                  0, &vectorlEIsotopicVectorgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<IsotopicVector>) );
      instance.SetNew(&new_vectorlEIsotopicVectorgR);
      instance.SetNewArray(&newArray_vectorlEIsotopicVectorgR);
      instance.SetDelete(&delete_vectorlEIsotopicVectorgR);
      instance.SetDeleteArray(&deleteArray_vectorlEIsotopicVectorgR);
      instance.SetDestructor(&destruct_vectorlEIsotopicVectorgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<IsotopicVector> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<IsotopicVector>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEIsotopicVectorgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<IsotopicVector>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEIsotopicVectorgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<IsotopicVector> : new vector<IsotopicVector>;
   }
   static void *newArray_vectorlEIsotopicVectorgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<IsotopicVector>[nElements] : new vector<IsotopicVector>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEIsotopicVectorgR(void *p) {
      delete ((vector<IsotopicVector>*)p);
   }
   static void deleteArray_vectorlEIsotopicVectorgR(void *p) {
      delete [] ((vector<IsotopicVector>*)p);
   }
   static void destruct_vectorlEIsotopicVectorgR(void *p) {
      typedef vector<IsotopicVector> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<IsotopicVector>

/********************************************************
* CLASSBackEndDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableCLASSBackEndDict();

extern "C" void G__set_cpp_environmentCLASSBackEndDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../include/CLASSBackEnd.hxx");
  G__cpp_reset_tagtableCLASSBackEndDict();
}
#include <new>
extern "C" int G__cpp_dllrevCLASSBackEndDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* CLASSBackEnd */
static int G__CLASSBackEndDict_493_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CLASSBackEnd* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CLASSBackEnd[n];
     } else {
       p = new((void*) gvp) CLASSBackEnd[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CLASSBackEnd;
     } else {
       p = new((void*) gvp) CLASSBackEnd;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSBackEnd));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((CLASSBackEnd*) G__getstructoffset())->GetDecayDataBank());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<IsotopicVector>* pobj;
         const vector<IsotopicVector> xobj = ((const CLASSBackEnd*) G__getstructoffset())->GetIVArray();
         pobj = new vector<IsotopicVector>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const CLASSBackEnd*) G__getstructoffset())->GetIVNumber());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const CLASSBackEnd*) G__getstructoffset())->GetStorageType());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const CLASSBackEnd*) G__getstructoffset())->GetOutBackEndFacility());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const IsotopicVector* pobj;
         const IsotopicVector xobj = ((const CLASSBackEnd*) G__getstructoffset())->GetIV((int) G__int(libp->para[0]));
         pobj = new IsotopicVector(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((CLASSBackEnd*) G__getstructoffset())->SetIsStorageType((bool) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((CLASSBackEnd*) G__getstructoffset())->SetIsStorageType();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLASSBackEnd*) G__getstructoffset())->SetDecayDataBank((DecayDataBank*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLASSBackEnd*) G__getstructoffset())->SetIVArray(*((vector<IsotopicVector>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLASSBackEnd*) G__getstructoffset())->SetOutBackEndFacility((CLASSBackEnd*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLASSBackEnd*) G__getstructoffset())->AddIV(*((IsotopicVector*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLASSBackEnd*) G__getstructoffset())->ClearIVArray();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) CLASSBackEnd::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CLASSBackEnd::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) CLASSBackEnd::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CLASSBackEnd::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CLASSBackEnd*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CLASSBackEnd::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CLASSBackEnd::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CLASSBackEnd::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CLASSBackEndDict_493_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CLASSBackEnd::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__CLASSBackEndDict_493_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   CLASSBackEnd* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new CLASSBackEnd(*(CLASSBackEnd*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSBackEnd));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CLASSBackEnd G__TCLASSBackEnd;
static int G__CLASSBackEndDict_493_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CLASSBackEnd*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CLASSBackEnd*) (soff+(sizeof(CLASSBackEnd)*i)))->~G__TCLASSBackEnd();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CLASSBackEnd*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CLASSBackEnd*) (soff))->~G__TCLASSBackEnd();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__CLASSBackEndDict_493_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CLASSBackEnd* dest = (CLASSBackEnd*) G__getstructoffset();
   *dest = *(CLASSBackEnd*) libp->para[0].ref;
   const CLASSBackEnd& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* CLASSBackEnd */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncCLASSBackEndDict {
 public:
  G__Sizep2memfuncCLASSBackEndDict(): p(&G__Sizep2memfuncCLASSBackEndDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncCLASSBackEndDict::*p)();
};

size_t G__get_sizep2memfuncCLASSBackEndDict()
{
  G__Sizep2memfuncCLASSBackEndDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceCLASSBackEndDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSBackEnd))) {
     CLASSBackEnd *G__Lderived;
     G__Lderived=(CLASSBackEnd*)0x1000;
     {
       CLASSFacility *G__Lpbase=(CLASSFacility*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSBackEnd),G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSFacility),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       CLASSObject *G__Lpbase=(CLASSObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSBackEnd),G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSBackEnd),G__get_linked_tagnum(&G__CLASSBackEndDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSBackEnd),G__get_linked_tagnum(&G__CLASSBackEndDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableCLASSBackEndDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<ZAI,double>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_maplEZAIcOdoublecOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<ZAI,double,less<ZAI> >",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_maplEZAIcOdoublecOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ZAI>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlEZAIcOallocatorlEZAIgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEZAIcOallocatorlEZAIgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlEZAIcOallocatorlEZAIgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEZAIcOallocatorlEZAIgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlEZAIcOallocatorlEZAIgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<ZAI,TGraph*>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_maplEZAIcOTGraphmUcOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOTGraphmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<ZAI,TGraph*,less<ZAI> >",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_maplEZAIcOTGraphmUcOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOTGraphmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<ZAI,EvolutionData>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_maplEZAIcOEvolutionDatacOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOEvolutionDatagRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<ZAI,EvolutionData,less<ZAI> >",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_maplEZAIcOEvolutionDatacOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOEvolutionDatagRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<IsotopicVector>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlEIsotopicVectorcOallocatorlEIsotopicVectorgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEIsotopicVectorcOallocatorlEIsotopicVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlEIsotopicVectorcOallocatorlEIsotopicVectorgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEIsotopicVectorcOallocatorlEIsotopicVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlEIsotopicVectorcOallocatorlEIsotopicVectorgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* CLASSBackEnd */
static void G__setup_memvarCLASSBackEnd(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSBackEnd));
   { CLASSBackEnd *p; p=(CLASSBackEnd*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlEIsotopicVectorcOallocatorlEIsotopicVectorgRsPgR),G__defined_typename("vector<IsotopicVector>"),-1,2,"fIVArray=",0,"/< Vector containning all the fuel stored.");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSBackEnd),-1,-1,2,"fOutBackEndFacility=",0,"!< Facility getting the fuel at the end of the cycle");
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"fIsStorageType=",0,"!< True if there is not OutBAckEndFacility (like a storage...)");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CLASSBackEndDictLN_DecayDataBank),-1,-1,4,"fDecayDataBase=",0,"!< Pointer to the Decay DataBase");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CLASSBackEndDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarCLASSBackEndDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncCLASSBackEnd(void) {
   /* CLASSBackEnd */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSBackEnd));
   G__memfunc_setup("CLASSBackEnd",1022,G__CLASSBackEndDict_493_0_1, 105, G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSBackEnd), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDecayDataBank",1532,G__CLASSBackEndDict_493_0_2, 85, G__get_linked_tagnum(&G__CLASSBackEndDictLN_DecayDataBank), -1, 0, 0, 1, 1, 0, "", "!< Return the pointer to the decay DataBank", (void*) NULL, 0);
   G__memfunc_setup("GetIVArray",958,G__CLASSBackEndDict_493_0_3, 117, G__get_linked_tagnum(&G__CLASSBackEndDictLN_vectorlEIsotopicVectorcOallocatorlEIsotopicVectorgRsPgR), G__defined_typename("vector<IsotopicVector>"), 0, 0, 1, 1, 8, "", "!< Return the IsotopicVector Array", (void*) NULL, 0);
   G__memfunc_setup("GetIVNumber",1064,G__CLASSBackEndDict_493_0_4, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetStorageType",1431,G__CLASSBackEndDict_493_0_5, 103, -1, -1, 0, 0, 1, 1, 8, "", "!< Return the storageType", (void*) NULL, 0);
   G__memfunc_setup("GetOutBackEndFacility",2069,G__CLASSBackEndDict_493_0_6, 85, G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSBackEnd), -1, 0, 0, 1, 1, 8, "", "!<Return the pointer to the OUtBackEndFacility", (void*) NULL, 0);
   G__memfunc_setup("GetIV",447,G__CLASSBackEndDict_493_0_7, 117, G__get_linked_tagnum(&G__CLASSBackEndDictLN_IsotopicVector), -1, 0, 1, 1, 1, 8, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetIsStorageType",1631,G__CLASSBackEndDict_493_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'true' val", "! Set the fIsStorage bool", (void*) NULL, 0);
   G__memfunc_setup("SetDecayDataBank",1544,G__CLASSBackEndDict_493_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "U 'DecayDataBank' - 0 - decayDB", "! Set the Decay DataBank", (void*) NULL, 0);
   G__memfunc_setup("SetIVArray",970,G__CLASSBackEndDict_493_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<IsotopicVector,allocator<IsotopicVector> >' 'vector<IsotopicVector>' 0 - ivarray", "!< Set The isotopicVector Array", (void*) NULL, 1);
   G__memfunc_setup("SetOutBackEndFacility",2081,G__CLASSBackEndDict_493_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "U 'CLASSBackEnd' - 0 - befacility", "! Set a Out Facility for the fuel", (void*) NULL, 1);
   G__memfunc_setup("AddIV",424,G__CLASSBackEndDict_493_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'IsotopicVector' - 0 - isotopicvector", "!< Add an Isotopicvector to the IVArray", (void*) NULL, 1);
   G__memfunc_setup("ClearIVArray",1157,G__CLASSBackEndDict_493_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", "!< Empty the IVArray removing all fuel stored", (void*) NULL, 0);
   G__memfunc_setup("GetDecay",774,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__CLASSBackEndDictLN_IsotopicVector), -1, 0, 2, 1, 2, 0, 
"u 'IsotopicVector' - 0 - isotopicvector n - 'cSecond' 0 - t", "!< Get IsotopicVector Decay at the t time", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__CLASSBackEndDict_493_0_15, 85, G__get_linked_tagnum(&G__CLASSBackEndDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&CLASSBackEnd::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__CLASSBackEndDict_493_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CLASSBackEnd::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__CLASSBackEndDict_493_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&CLASSBackEnd::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__CLASSBackEndDict_493_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&CLASSBackEnd::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__CLASSBackEndDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__CLASSBackEndDict_493_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__CLASSBackEndDict_493_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CLASSBackEnd::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__CLASSBackEndDict_493_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CLASSBackEnd::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__CLASSBackEndDict_493_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CLASSBackEnd::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__CLASSBackEndDict_493_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CLASSBackEnd::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("CLASSBackEnd", 1022, G__CLASSBackEndDict_493_0_27, (int) ('i'), G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSBackEnd), -1, 0, 1, 1, 1, 0, "u 'CLASSBackEnd' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~CLASSBackEnd", 1148, G__CLASSBackEndDict_493_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__CLASSBackEndDict_493_0_29, (int) ('u'), G__get_linked_tagnum(&G__CLASSBackEndDictLN_CLASSBackEnd), -1, 1, 1, 1, 1, 0, "u 'CLASSBackEnd' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncCLASSBackEndDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalCLASSBackEndDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcCLASSBackEndDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__CLASSBackEndDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_CLASSObject = { "CLASSObject" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_IsotopicVector = { "IsotopicVector" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_maplEZAIcOdoublecOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOdoublegRsPgRsPgR = { "map<ZAI,double,less<ZAI>,allocator<pair<const ZAI,double> > >" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_vectorlEZAIcOallocatorlEZAIgRsPgR = { "vector<ZAI,allocator<ZAI> >" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEZAIcOallocatorlEZAIgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ZAI,allocator<ZAI> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_maplEZAIcOTGraphmUcOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOTGraphmUgRsPgRsPgR = { "map<ZAI,TGraph*,less<ZAI>,allocator<pair<const ZAI,TGraph*> > >" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_DecayDataBank = { "DecayDataBank" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_maplEZAIcOEvolutionDatacOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOEvolutionDatagRsPgRsPgR = { "map<ZAI,EvolutionData,less<ZAI>,allocator<pair<const ZAI,EvolutionData> > >" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_CLASSFacility = { "CLASSFacility" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_CLASSBackEnd = { "CLASSBackEnd" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_vectorlEIsotopicVectorcOallocatorlEIsotopicVectorgRsPgR = { "vector<IsotopicVector,allocator<IsotopicVector> >" , 99 , -1 };
G__linked_taginfo G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEIsotopicVectorcOallocatorlEIsotopicVectorgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<IsotopicVector,allocator<IsotopicVector> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableCLASSBackEndDict() {
  G__CLASSBackEndDictLN_TClass.tagnum = -1 ;
  G__CLASSBackEndDictLN_TBuffer.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMemberInspector.tagnum = -1 ;
  G__CLASSBackEndDictLN_TObject.tagnum = -1 ;
  G__CLASSBackEndDictLN_TNamed.tagnum = -1 ;
  G__CLASSBackEndDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_CLASSObject.tagnum = -1 ;
  G__CLASSBackEndDictLN_IsotopicVector.tagnum = -1 ;
  G__CLASSBackEndDictLN_maplEZAIcOdoublecOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOdoublegRsPgRsPgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_vectorlEZAIcOallocatorlEZAIgRsPgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEZAIcOallocatorlEZAIgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_maplEZAIcOTGraphmUcOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOTGraphmUgRsPgRsPgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_DecayDataBank.tagnum = -1 ;
  G__CLASSBackEndDictLN_maplEZAIcOEvolutionDatacOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOEvolutionDatagRsPgRsPgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_CLASSFacility.tagnum = -1 ;
  G__CLASSBackEndDictLN_CLASSBackEnd.tagnum = -1 ;
  G__CLASSBackEndDictLN_vectorlEIsotopicVectorcOallocatorlEIsotopicVectorgRsPgR.tagnum = -1 ;
  G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEIsotopicVectorcOallocatorlEIsotopicVectorgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableCLASSBackEndDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_CLASSObject);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_IsotopicVector);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_maplEZAIcOdoublecOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_vectorlEZAIcOallocatorlEZAIgRsPgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEZAIcOallocatorlEZAIgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_maplEZAIcOTGraphmUcOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOTGraphmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_DecayDataBank);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_maplEZAIcOEvolutionDatacOlesslEZAIgRcOallocatorlEpairlEconstsPZAIcOEvolutionDatagRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_CLASSFacility);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_CLASSBackEnd),sizeof(CLASSBackEnd),-1,61696,(char*)NULL,G__setup_memvarCLASSBackEnd,G__setup_memfuncCLASSBackEnd);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_vectorlEIsotopicVectorcOallocatorlEIsotopicVectorgRsPgR);
   G__get_linked_tagnum_fwd(&G__CLASSBackEndDictLN_reverse_iteratorlEvectorlEIsotopicVectorcOallocatorlEIsotopicVectorgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupCLASSBackEndDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupCLASSBackEndDict()");
  G__set_cpp_environmentCLASSBackEndDict();
  G__cpp_setup_tagtableCLASSBackEndDict();

  G__cpp_setup_inheritanceCLASSBackEndDict();

  G__cpp_setup_typetableCLASSBackEndDict();

  G__cpp_setup_memvarCLASSBackEndDict();

  G__cpp_setup_memfuncCLASSBackEndDict();
  G__cpp_setup_globalCLASSBackEndDict();
  G__cpp_setup_funcCLASSBackEndDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncCLASSBackEndDict();
  return;
}
class G__cpp_setup_initCLASSBackEndDict {
  public:
    G__cpp_setup_initCLASSBackEndDict() { G__add_setup_func("CLASSBackEndDict",(G__incsetup)(&G__cpp_setupCLASSBackEndDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initCLASSBackEndDict() { G__remove_setup_func("CLASSBackEndDict"); }
};
G__cpp_setup_initCLASSBackEndDict G__cpp_setup_initializerCLASSBackEndDict;

